// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Atlantis.Simple.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Atlantis.Simple {
  public static partial class AtlantisService
  {
    static readonly string __ServiceName = "Atlantis.Simple.AtlantisService";

    static readonly grpc::Marshaller<global::Atlantis.Simple.HelloMessage> __Marshaller_Atlantis_Simple_HelloMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Atlantis.Simple.HelloMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Atlantis.Simple.HelloMessageResult> __Marshaller_Atlantis_Simple_HelloMessageResult = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Atlantis.Simple.HelloMessageResult.Parser.ParseFrom);

    static readonly grpc::Method<global::Atlantis.Simple.HelloMessage, global::Atlantis.Simple.HelloMessageResult> __Method_Hello = new grpc::Method<global::Atlantis.Simple.HelloMessage, global::Atlantis.Simple.HelloMessageResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Hello",
        __Marshaller_Atlantis_Simple_HelloMessage,
        __Marshaller_Atlantis_Simple_HelloMessageResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Atlantis.Simple.AtlantisSimpleReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AtlantisService</summary>
    public abstract partial class AtlantisServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Atlantis.Simple.HelloMessageResult> Hello(global::Atlantis.Simple.HelloMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AtlantisService</summary>
    public partial class AtlantisServiceClient : grpc::ClientBase<AtlantisServiceClient>
    {
      /// <summary>Creates a new client for AtlantisService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AtlantisServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AtlantisService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AtlantisServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AtlantisServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AtlantisServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Atlantis.Simple.HelloMessageResult Hello(global::Atlantis.Simple.HelloMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Hello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Atlantis.Simple.HelloMessageResult Hello(global::Atlantis.Simple.HelloMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Hello, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Atlantis.Simple.HelloMessageResult> HelloAsync(global::Atlantis.Simple.HelloMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Atlantis.Simple.HelloMessageResult> HelloAsync(global::Atlantis.Simple.HelloMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Hello, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AtlantisServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AtlantisServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AtlantisServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Hello, serviceImpl.Hello).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AtlantisServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Hello, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Atlantis.Simple.HelloMessage, global::Atlantis.Simple.HelloMessageResult>(serviceImpl.Hello));
    }

  }
}
#endregion
